[book]
title = "Substrukt Documentation"
authors = ["Wavefunk"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "coal"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/wavefunk/substrukt"
site-url = "/"
